name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    name: Typecheck
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      # we build packages before typechecking to ensure examples/ dir use correct packages they are up-to-date
      - name: Build Packages
        run: pnpm --filter "./packages/**" build

      - name: Typecheck
        # use tsgo instead of tsc
        run: pnpm tsgo -b --noEmit
